name: JSDoc generation

on:
  push:
    branches:
      - main # Specifies that the workflow will only run on pushes to main

jobs: # the things being executed
  tests: # the name of your status check, will become important when you do branch protection
    runs-on: ubuntu-latest # which device on Github's server that you are running the Actions on
    steps:
      - uses: actions/checkout@v4 # using version 4 of Actions
      - name: Install Dependencies
        run: npm install
      - name: Install JSDoc
        run: npm install -g jsdoc
      - name: Build JSDocs
        run: |
          rm -rf ./jsdoc
          jsdoc -r ./source/modules/journal source/modules/file_explorer source/modules/models -d ./jsdoc
      - name: Create Pull Request for update JSDoc
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-jsdoc
          title: Update JSDoc documentation
          body: |
            This pull request updates the JSDoc documentation.
          commit-message: Update JSDoc documentation
