name: Unit Tests # name of the test

on: [push] # the Github Action will activate "on" the event that you "push" to the repo

jobs: # the things being executed
  tests: # the name of your status check, will become important when you do branch protection
    runs-on: ubuntu-latest # which device on Github's server that you are running the Actions on
    steps:
      - uses: actions/checkout@v4 # using version 4 of Actions
      - name: Install Dependencies
        run: npm install
      - name: Unit Test
        run: npm test ./__tests__/unit.test.js # the actual testing line
      - name: Default Storage Test
        run: npm test ./source/Backend/src/filestore.test.js # This should run the tests in filestore.js
      #- name: Codacy Analysis CLI #Codacy standard test
      #  uses: codacy/codacy-analysis-cli-action@v4.4.0
      #- name: generate JSDoc page
      #  run: jsdoc functions.js
